name: PHP CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Check-out repository under GitHub workspace
      - uses: actions/checkout@v2
        # Step's name
      - name: Setup PHP
        # Action gives to setup the PHP environment to test application
        uses: shivammathur/setup-php@v2
        with:
          # Specify the PHP version
          php-version: '7.4.14'
      - name: Install
        # Install project
        run: make install
      - name: Run linter
        # Run Linter
        run: make lint
      - name: Run test & publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{34828a17cdf3058df4ab707ea59daeb1d8526121c6a1d9375d351fbefc60043e}}
        with:
          coverageCommand: make test-coverage
          coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
          debug: true